# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 
  host: localhost
  port: 5432
  
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: formularioEvaluado_development


test:
  <<: *default
  database: formularioEvaluado_test


production:
  url: <%= ENV["DATABASE_URL"] %>



